# Generated by Django 4.0.4 on 2022-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0003_champion_lore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='lore',
            field=models.CharField(blank=True, help_text="Enter Champion's Lore", max_length=500, null=True, verbose_name='Champion Lore'),
        ),
    ]
